### ISSUE TITLE
Recaptcha missing from OnePage checkout page.

### ISSUE THREAD

**Issue by epiblue** [noglitchyo/mage-google-recaptcha#2]
Can you tell me how to add the recaptcha on the  /persistent/checkout/onepage/login.phtml ? 

Because now it's not present, but the system requires it...

Or simply disable it for that page only... The checkout page..

Thank for the help

**Comment by noglitchyo** [comment]
Hello @epiblue ,

Thank you for your feedback. Indeed, I forgot to display the reCAPTCHA on checkout for the login form.
It is now fully working, and disabling the customer_login in your configuration will disable it on the checkout as well. You must keep in mind that the customer_login setting is used for the checkout login and the customer account login since they are using the same actions.

You can find the fix in the last release 1.0.1

Cheers!
